print("Hello, World")
print("a maré tá cheia")
print("tá, tá, tá, tá, tá")
print("cheia de sereia")
print("e o timão")
print("querendo golear")
print("caiu na rede")
print("é peixe")
print("lê-lê-ah")
print("O timâo vai golear")